"""create tasks and task_dependencies tables

Revision ID: 5c29f598c44d
Revises: 
Create Date: 2025-08-25 16:12:41.538688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c29f598c44d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('level_priority', sa.String(), nullable=False),
    sa.CheckConstraint("level_priority IN ('Low', 'Medium', 'High')", name='check_priority'),
    sa.CheckConstraint("status IN ('Incomplete', 'Completed')", name='check_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_description')
    )
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'depends_on_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_dependencies')
    op.drop_table('tasks')
    # ### end Alembic commands ###
